#!/bin/sh

set -e

case "$1" in
    configure)
        source /tmp/session_bus_address.user
        /usr/bin/dbus-send --print-reply --dest=com.meego.core.MNotificationManager \
        /notificationmanager com.meego.core.MNotificationManager.addNotification \
        uint32:0 uint32:0 string:'device' \
        string:'' string:'Camera+ installed. Please restart your phone!' string:'' \
        string:'icon-m-toolbar-done' uint32:0 > /dev/null 2>&1
        ;;
esac

#DEBHELPER#

exit 0
